# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c02bb8e52453f4af307f843cbbb2825722eae711df07380253e1672b360c7f4d7ca1bbdbc79a72a1792c4509ab37577cd6242f548b634bf61b114efa8c77c2be

test:
  secret_key_base: b4b5c22fe7894e11b8b3d3a61ceaa98c8e8e89aa42475fb32279a9e04ccbb18eb34118fb829289895bc060f29a18447ec69ae091baa4abe65479d62acc7d7403

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
